//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player inputs"",
            ""id"": ""3a60a1ef-41a1-4b2a-a947-5f10fa789e6c"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8451a5d5-0c20-4c76-80ad-d68bf035cc1f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2,StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ConfirmButton"",
                    ""type"": ""Button"",
                    ""id"": ""a02f28bf-cf16-4d57-89cc-066e07343a35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""b70b0563-d208-4508-bcca-333be2772fa1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GoBack"",
                    ""type"": ""Button"",
                    ""id"": ""e58c72e9-df8a-4d38-8462-b3e1a4d37b82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuUp"",
                    ""type"": ""Button"",
                    ""id"": ""0cdf3f41-0971-493b-b22c-fa9014355509"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuDown"",
                    ""type"": ""Button"",
                    ""id"": ""84ad45ec-f0b3-43b0-8055-3ec39f1af90c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f6cfda8f-ce41-4344-ad4b-51ccddc1c710"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuRight"",
                    ""type"": ""Button"",
                    ""id"": ""99cecab3-f8c8-4c17-ab21-03d66b9e2aee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""81c1ce43-0fde-4372-b056-d60a800c5e7d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""538a3e28-74a9-4d16-9fdb-4b77ea7a29cf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2cb6eaf2-86b7-4604-aae8-45b1863e233e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6c2ebeb4-5064-4e4a-9b92-35ad2a2c28ec"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""95b5f5da-4c74-45d8-b3b7-db1130e45477"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""DPAD"",
                    ""id"": ""5679dfc2-8227-4ba1-94ac-1f712c9c70a9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""55322671-7ab5-4800-873c-f3ebda031d79"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2b39e22d-8356-410f-9395-cd680696211d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1f86896a-6964-44f1-ba0d-2a4d66b59593"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2ba49775-9bd0-4a31-b52e-d73de2c79e55"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2c24d474-263f-49df-9c62-e599cfb9f21d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67378365-e311-4236-acfa-4e308433f538"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b131bfc8-3028-4bea-8fd3-eb1a500246db"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07ee82b5-3034-43e4-ab12-5bce336e399a"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7d26ccb-db9e-4e3e-9449-2abee8b71f41"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5e75794-5357-4e21-a22d-ebece618a7f6"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbd1da5a-31e6-4c38-b84c-7fcd6d55e6b2"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0fa22f1-333f-43d4-9303-4e7d85244215"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4014537-e6be-4c64-8ad6-9a68468bd51d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c168fa4-245a-4593-bd9c-b88147934c7d"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b98b4460-f9ca-4bc7-9920-d95f02ce348b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player inputs
        m_Playerinputs = asset.FindActionMap("Player inputs", throwIfNotFound: true);
        m_Playerinputs_Move = m_Playerinputs.FindAction("Move", throwIfNotFound: true);
        m_Playerinputs_ConfirmButton = m_Playerinputs.FindAction("ConfirmButton", throwIfNotFound: true);
        m_Playerinputs_MenuButton = m_Playerinputs.FindAction("MenuButton", throwIfNotFound: true);
        m_Playerinputs_GoBack = m_Playerinputs.FindAction("GoBack", throwIfNotFound: true);
        m_Playerinputs_MenuUp = m_Playerinputs.FindAction("MenuUp", throwIfNotFound: true);
        m_Playerinputs_MenuDown = m_Playerinputs.FindAction("MenuDown", throwIfNotFound: true);
        m_Playerinputs_MenuLeft = m_Playerinputs.FindAction("MenuLeft", throwIfNotFound: true);
        m_Playerinputs_MenuRight = m_Playerinputs.FindAction("MenuRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player inputs
    private readonly InputActionMap m_Playerinputs;
    private IPlayerinputsActions m_PlayerinputsActionsCallbackInterface;
    private readonly InputAction m_Playerinputs_Move;
    private readonly InputAction m_Playerinputs_ConfirmButton;
    private readonly InputAction m_Playerinputs_MenuButton;
    private readonly InputAction m_Playerinputs_GoBack;
    private readonly InputAction m_Playerinputs_MenuUp;
    private readonly InputAction m_Playerinputs_MenuDown;
    private readonly InputAction m_Playerinputs_MenuLeft;
    private readonly InputAction m_Playerinputs_MenuRight;
    public struct PlayerinputsActions
    {
        private @InputActions m_Wrapper;
        public PlayerinputsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Playerinputs_Move;
        public InputAction @ConfirmButton => m_Wrapper.m_Playerinputs_ConfirmButton;
        public InputAction @MenuButton => m_Wrapper.m_Playerinputs_MenuButton;
        public InputAction @GoBack => m_Wrapper.m_Playerinputs_GoBack;
        public InputAction @MenuUp => m_Wrapper.m_Playerinputs_MenuUp;
        public InputAction @MenuDown => m_Wrapper.m_Playerinputs_MenuDown;
        public InputAction @MenuLeft => m_Wrapper.m_Playerinputs_MenuLeft;
        public InputAction @MenuRight => m_Wrapper.m_Playerinputs_MenuRight;
        public InputActionMap Get() { return m_Wrapper.m_Playerinputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerinputsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerinputsActions instance)
        {
            if (m_Wrapper.m_PlayerinputsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMove;
                @ConfirmButton.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnConfirmButton;
                @ConfirmButton.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnConfirmButton;
                @ConfirmButton.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnConfirmButton;
                @MenuButton.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuButton;
                @MenuButton.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuButton;
                @MenuButton.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuButton;
                @GoBack.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnGoBack;
                @GoBack.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnGoBack;
                @GoBack.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnGoBack;
                @MenuUp.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuUp;
                @MenuUp.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuUp;
                @MenuUp.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuUp;
                @MenuDown.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuDown;
                @MenuDown.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuDown;
                @MenuDown.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuDown;
                @MenuLeft.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuLeft;
                @MenuLeft.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuLeft;
                @MenuRight.started -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuRight;
                @MenuRight.performed -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuRight;
                @MenuRight.canceled -= m_Wrapper.m_PlayerinputsActionsCallbackInterface.OnMenuRight;
            }
            m_Wrapper.m_PlayerinputsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @ConfirmButton.started += instance.OnConfirmButton;
                @ConfirmButton.performed += instance.OnConfirmButton;
                @ConfirmButton.canceled += instance.OnConfirmButton;
                @MenuButton.started += instance.OnMenuButton;
                @MenuButton.performed += instance.OnMenuButton;
                @MenuButton.canceled += instance.OnMenuButton;
                @GoBack.started += instance.OnGoBack;
                @GoBack.performed += instance.OnGoBack;
                @GoBack.canceled += instance.OnGoBack;
                @MenuUp.started += instance.OnMenuUp;
                @MenuUp.performed += instance.OnMenuUp;
                @MenuUp.canceled += instance.OnMenuUp;
                @MenuDown.started += instance.OnMenuDown;
                @MenuDown.performed += instance.OnMenuDown;
                @MenuDown.canceled += instance.OnMenuDown;
                @MenuLeft.started += instance.OnMenuLeft;
                @MenuLeft.performed += instance.OnMenuLeft;
                @MenuLeft.canceled += instance.OnMenuLeft;
                @MenuRight.started += instance.OnMenuRight;
                @MenuRight.performed += instance.OnMenuRight;
                @MenuRight.canceled += instance.OnMenuRight;
            }
        }
    }
    public PlayerinputsActions @Playerinputs => new PlayerinputsActions(this);
    public interface IPlayerinputsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnConfirmButton(InputAction.CallbackContext context);
        void OnMenuButton(InputAction.CallbackContext context);
        void OnGoBack(InputAction.CallbackContext context);
        void OnMenuUp(InputAction.CallbackContext context);
        void OnMenuDown(InputAction.CallbackContext context);
        void OnMenuLeft(InputAction.CallbackContext context);
        void OnMenuRight(InputAction.CallbackContext context);
    }
}
